# Generated by Django 4.0.8 on 2022-10-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=200)),
                ('backend', models.BooleanField()),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=250)),
            ],
        ),
    ]
